### ISSUE TITLE
Data release

### ISSUE THREAD

**Issue by zhangmozhe** [large-ocr-model/large-ocr-model.github.io#3]
Thanks for your great work! Just wonder whether the dataset will be released? And when will the data be planned to be released?

**Comment by large-ocr-model** [comment]
We have already open-sourced the dataset, please refer to the [Data.md](https://github.com/large-ocr-model/large-ocr-model.github.io/blob/main/Data.md) for more details..

**Comment by zhangmozhe** [comment]
Got it. Many thanks!
