### ISSUE TITLE
Alternate checkpoint download link

### ISSUE THREAD

**Issue by morgankohler** [large-ocr-model/large-ocr-model.github.io#4]
Hi, appreciate the work and the released code / model. I am wondering if you may consider uploading the checkpoint to another location as it is difficult for me to download from Baidu. Thanks!

**Comment by large-ocr-model** [comment]
Additional download links can be found in [GoogleYun](https://drive.google.com/file/d/1Fj2KCH8gvlyMBeGvsy8ZhHYO_IIXr76u/view?usp=sharing)
